apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraMounts:
      # allow Falco to use devices provided by the kernel module
      - hostPath: /dev
        containerPath: /dev
      # allow Falco to use the Docker unix socket
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock
  - role: worker
    extraMounts:
      # allow Falco to use devices provided by the kernel module
      - hostPath: /dev
        containerPath: /dev
      # allow Falco to use the Docker unix socket
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock
  - role: worker
    extraMounts:
      # allow Falco to use devices provided by the kernel module
      - hostPath: /dev
        containerPath: /dev
      # allow Falco to use the Docker unix socket
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock
