apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
    - name: busybox
      image: busybox:1.35.0
      imagePullPolicy: IfNotPresent
      command: [ "sh", "-c", "sleep 1h" ]
      resources:
        requests:
          cpu: 100m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 32Mi
