apiVersion: v1
kind: Pod
metadata:
  name: insecure
spec:
  containers:
    - name: insecure
      image: busybox:1.35.0
      imagePullPolicy: IfNotPresent
      command: [ "sh", "-c", "sleep 1h" ]
      resources:
        requests:
          cpu: 100m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 32Mi
      volumeMounts:
        - name: empty-dir
          mountPath: /data/demo
  volumes:
    - name: empty-dir
      emptyDir: {}
