apiVersion: v1
kind: Service
metadata:
  name: polaris-dashboard
  namespace: polaris
spec:
  selector:
    app: polaris
  ports:
    - name: http-dashboard
      port: 8080
      targetPort: http-dashboard
