apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-portforward-only
rules:
  - apiGroups:
      - ""
    resources:
      - pods/portforward
    verbs:
      - get
      - list
      - create
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - get
      - list
      - watch
