apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
  - name: DefaultPodSecurity
    configuration:
      apiVersion: pod-security.admission.config.k8s.io/v1alpha1
      kind: PodSecurityConfiguration
      defaults:
        enforce: "baseline"
        enforce-version: "latest"
        warn: "restricted"
        warn-version: "latest"
        audit: "restricted"
        audit-version: "latest"
      exemptions:
        usernames: []
        runtimeClassNames: []
        namespaces: [kube-system]
